apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: built-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/jhomar-welcome-github/welcome-nodejs-github
