apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-trigger-binding
spec:
  params:
    - name: git-driver
      value: github
    - name: git-revision
      value: $(body.head_commit.id)
    - name: git-repo-url
      value: $(body.repository.clone_url)
    - name: git-repo-name
      value: $(body.repository.name)
    - name: git-repo-path
      value: $(body.repository.full_name)
    - name: git-ref
      value: $(extensions.git-ref)
