apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "welcome-nodejs-github-pipeline-pvc"
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2-encrypted
spec:
  storageClassName: gp2-encrypted
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi