apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: npm-test
spec:
  workspaces:
    - name: source
  steps:
    - name: test
      image: quay.io/bitnami/node:12
      command:
        - /bin/sh
        - -c
      args:
        - npm run test
      workingDir: $(workspaces.source.path)
